# Generated by Django 3.1 on 2008-12-31 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20090101_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermiddateSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iskill', models.CharField(max_length=15)),
                ('psi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IntermiddateSkills', to='user.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='BeginnerSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bskill', models.CharField(max_length=15)),
                ('psb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BeginnerSkills', to='user.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askill', models.CharField(max_length=15)),
                ('psa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdvancedSkills', to='user.Portfolio')),
            ],
        ),
    ]
