# Generated by Django 3.1 on 2008-12-31 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_advancedskills_beginnerskills_intermiddateskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedskills',
            name='psa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdvancedSkills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beginnerskills',
            name='psb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BeginnerSkills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intermiddateskills',
            name='psi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IntermiddateSkills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='ps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolioproject', to=settings.AUTH_USER_MODEL),
        ),
    ]
