# Generated by Django 3.1 on 2008-12-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20090101_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(default='https://127.0.0.1:8000', max_length=60),
        ),
    ]
