# Generated by Django 3.1 on 2008-12-31 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='name',
            field=models.CharField(default='Course Name', max_length=60),
        ),
        migrations.AddField(
            model_name='courses',
            name='owner',
            field=models.CharField(default='Incognito', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.CharField(default='Free', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='rating',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='tag',
            field=models.CharField(default='Beginner', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='weblink',
            field=models.URLField(default='http://www.youtube.com', unique=True),
            preserve_default=False,
        ),
    ]
