# Generated by Django 3.1 on 2008-12-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20090101_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(default='security_analyst-card-1024x634.jpg', upload_to='coursesthumb'),
        ),
    ]
