# Generated by Django 3.1 on 2008-12-31 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('resumeurl', models.URLField(max_length=80, unique=True)),
                ('avatar', models.ImageField(default='avatar/defaultavatar.jpg', upload_to='avatar')),
                ('usern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=60)),
                ('purl', models.URLField()),
                ('pdesp', models.TextField()),
                ('pimage', models.ImageField(upload_to='projectimage')),
                ('ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolioproject', to='user.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='IntermiddateSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iskill', models.CharField(max_length=15)),
                ('psi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IntermiddateSkills', to='user.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='BeginnerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bskill', models.CharField(max_length=15)),
                ('psb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BeginnerSkills', to='user.Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='AdvancedSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askill', models.CharField(max_length=15)),
                ('psa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdvancedSkills', to='user.Portfolio')),
            ],
        ),
    ]
