# Generated by Django 3.1 on 2008-12-31 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beginnerskill',
            name='psb',
        ),
        migrations.RemoveField(
            model_name='intermiddateskill',
            name='psi',
        ),
        migrations.DeleteModel(
            name='AdvancedSkill',
        ),
        migrations.DeleteModel(
            name='BeginnerSkill',
        ),
        migrations.DeleteModel(
            name='IntermiddateSkill',
        ),
    ]
